version: '3.7'

services:
  db:
    image: 'mongo:latest'
    container_name: aiohttp-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - '27017:27017'
    networks:
      - net

  backend:
    build: .
    container_name: aiohttp
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - net

networks:
  net:
